# Generate secret with base64 encoded password with eg: echo -n 'rootpassword' | base64 and store in GitHub secrets
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tecvinson-app
type: Opaque
data:
  mysql-root-password: REPLACE_WITH_BASE64_PASSWORD

