apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tecvinson-app  
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: frontend
        image: 861276076873.dkr.ecr.us-east-1.amazonaws.com/frontend-repository:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
          - "-nginx.scrape-uri=http://127.0.0.1:80/stub_status"
        ports:
        - containerPort: 9113
          name: metrics
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "200m"