apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: tecvinson-app
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Ensure NGINX Ingress controller is targeted
    # You can add other annotations here if you need specific NGINX configuration
spec:
  rules:
  - host: frontend.example.com
    http:
      paths:
      - path: /devops-uno
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
